#!/usr/bin/env python3
import sys
import warnings
import argparse
import yaml
from monolaunch.monoparam import SourceLoader, Link, deep_copy_skip_empty, SimpleYAMLDumper

def formatwarning(message, category, filename, lineno, line=None): # type: ignore
    return "".join(
        f"# {'     ' if i else 'WARN:'} {line}\n"
        for i, line in enumerate(str(message).splitlines()) # type: ignore
    )
warnings.formatwarning = formatwarning

parser = argparse.ArgumentParser("yaml loader")
parser.add_argument("--skip-empty", action="store_true", help="skip null and empty mapping")
# TODO: --keep-tags: leave unknown tag untouched
parser.add_argument("link", help="link of yaml file to load")
args = parser.parse_args()

link = Link.parse(args.link)
link = Link(link.filepath.resolve(), link.fieldpath)

loader = SourceLoader()
node, _depends = loader.load(link)
data = None
if node is not None:
    data, _depends = loader.resolve_all(node)
if args.skip_empty:
    data = deep_copy_skip_empty(data)

data_str = yaml.dump(data, Dumper=SimpleYAMLDumper, sort_keys=False)

sys.stderr.flush()
print(data_str)
